# Generated by Django 5.0.1 on 2025-11-20 19:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('otp_code', models.CharField(max_length=6)),
                ('purpose', models.CharField(choices=[('login', 'Login'), ('signup', 'Sign Up'), ('password_reset', 'Password Reset')], default='login', max_length=20)),
                ('is_used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'otps',
                'indexes': [models.Index(fields=['email', 'purpose', 'is_used'], name='otps_email_32bf71_idx'), models.Index(fields=['expires_at'], name='otps_expires_f6308f_idx')],
            },
        ),
    ]
